name: "Check"
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: nix-tools
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13
    - name: Check flake
      run: nix flake check --impure
    - name: Build Neovim
      run: nix build .#nvim
    - name: Lint Lua
      run: nix develop --impure --command luacheck nvim/lua
    - name: Headless Smoke Test
      run: nix run .#nvim -- --headless +qa
    - name: Check formatting
      run: nix fmt -- --ci
