name: "Update Neovim Source"
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch: # Allow manual triggers
concurrency:
  group: update-neovim
  cancel-in-progress: true
jobs:
  neovim:
    uses: ./.github/workflows/flake-update.yml
    with:
      update-args: nixpkgs-neovim
      branch: update-neovim-src
      title: "chore: update neovim-version"
      body: "Updates the `nixpkgs-neovim` input in `flake.lock` to the latest on the stable channel, providing the latest stable release of Neovim."
    secrets: inherit
